name: Python CI
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install --upgrade pip flake8 black bandit pytest pexpect
      - name: Run black
        run: black --check .
      - name: Run flake8
        run: flake8 .
      - name: Run bandit
        run: bandit -r . -ll
      - name: Run pytest
        run: sudo pytest tests/test.py
